### ISSUE TITLE
UnicodeEncodeError when traceback contains non-ascii character

### ISSUE THREAD

**Issue by fiatjaf** [MindscapeHQ/raygun4py#23]
Here's what I got:

```python
Traceback (most recent call last):
  File "/home/fiatjaf/comp/wft/model-updates/reader.py", line 49, in process_messages
    done = process_message(payload)
  File "/home/fiatjaf/comp/wft/model-updates/reader.py", line 74, in process_message
    tags=['boardSetup']
  File "/home/fiatjaf/comp/wft/model-updates/venv/local/lib/python2.7/site-packages/raygun4py/raygunprovider.py", line 76, in send_exception
    errorMessage = raygunmsgs.RaygunErrorMessage(exc_type, exc_value, exc_traceback, options)
  File "/home/fiatjaf/comp/wft/model-updates/venv/local/lib/python2.7/site-packages/raygun4py/raygunmsgs.py", line 129, in __init__
    'localVariables': self._get_locals(frame[0]) if 'transmitLocalVariables' in options and options['transmitLocalVariables'] is True else None
  File "/home/fiatjaf/comp/wft/model-updates/venv/local/lib/python2.7/site-packages/raygun4py/raygunmsgs.py", line 145, in _get_locals
    result[key] = str(localVars[key])
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 2: ordinal not in range(128
```

My function call does not show entirely there, but it is

```python
            raygun.set_user(payload['username'])
            raygun.send_exception(
                exc_info=sys.exc_info(),
                userCustomData={'board_id': payload['board_id']},
                tags=['boardSetup']
            )
```

So, there is nothing non-ascii there, but I know there would be non-ascii characters in the traceback if it was going to be printed to stdout (there is a variable holding the value `idéias`, which has the character `u'\xe9' in position 2` as mentioned in the error above), so the problem is probably there.

**Comment by fundead** [comment]
This issue should now be resolved in the latest release above, which will be uploaded to pypi shortly.

**Comment by fiatjaf** [comment]
Thank you.
