### ISSUE TITLE
Possible bug in RaygunSender._post?

### ISSUE THREAD

**Issue by donspaulding** [MindscapeHQ/raygun4py#40]
It appears that the following line encounters a NameError when attempts to refer to `log` on the RaygunSender class without using the class or self to make the reference.

https://github.com/MindscapeHQ/raygun4py/blob/master/python2/raygun4py/raygunprovider.py#L167

It appears to me that this line should read `self.log.error(...)` as opposed to `log.error(...)`.

I hit this, but I'm doing some rather hackish things with RaygunSender at the moment, and so I'm not confident the bug is on the raygun4py side as opposed to within my own usage of it.

Here's the traceback:

```
Traceback (most recent call last):
  File "code/manage.py", line 8, in <module>
    execute_from_command_line(sys.argv)
  File "/var/projects/myproject/virtualenv/local/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/var/projects/myproject/virtualenv/local/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 346, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/var/projects/myproject/virtualenv/local/local/lib/python2.7/site-packages/django/core/management/base.py", line 394, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/var/projects/myproject/virtualenv/local/local/lib/python2.7/site-packages/django/core/management/base.py", line 445, in execute
    output = self.handle(*args, **options)

  ... snip a few frames that basically just call myinstance.save() ...

  File "/var/projects/myproject/virtualenv/local/local/lib/python2.7/site-packages/django/db/models/base.py", line 734, in save
    force_update=force_update, update_fields=update_fields)
  File "/var/projects/myproject/virtualenv/local/local/lib/python2.7/site-packages/django/db/models/base.py", line 762, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/var/projects/myproject/virtualenv/local/local/lib/python2.7/site-packages/django/db/models/base.py", line 827, in _save_table
    forced_update)
  File "/var/projects/myproject/virtualenv/local/local/lib/python2.7/site-packages/django/db/models/base.py", line 877, in _do_update
    return filtered._update(values) > 0
  File "/var/projects/myproject/virtualenv/local/local/lib/python2.7/site-packages/django/db/models/query.py", line 580, in _update
    return query.get_compiler(self.db).execute_sql(CURSOR)
  File "/var/projects/myproject/virtualenv/local/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 1062, in execute_sql
    cursor = super(SQLUpdateCompiler, self).execute_sql(result_type)
  File "/var/projects/myproject/virtualenv/local/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 829, in execute_sql
    sql, params = self.as_sql()
  File "/var/projects/myproject/virtualenv/local/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 1030, in as_sql
    val = field.get_db_prep_save(val, connection=self.connection)
  File "/var/projects/myproject/virtualenv/local/local/lib/python2.7/site-packages/django/db/models/fields/__init__.py", line 710, in get_db_prep_save
    prepared=False)
  File "/var/projects/myproject/virtualenv/local/local/lib/python2.7/site-packages/django/db/models/fields/__init__.py", line 1482, in get_db_prep_value
    value = self.get_prep_value(value)
  File "/var/projects/myproject/virtualenv/local/local/lib/python2.7/site-packages/django/db/models/fields/__init__.py", line 1474, in get_prep_value
    RuntimeWarning)
  File "/usr/lib/python2.7/logging/__init__.py", line 1720, in _showwarning
    logger.warning("%s", s)
  File "/usr/lib/python2.7/logging/__init__.py", line 1171, in warning
    self._log(WARNING, msg, args, **kwargs)
  File "/usr/lib/python2.7/logging/__init__.py", line 1278, in _log
    self.handle(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 1288, in handle
    self.callHandlers(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 1328, in callHandlers
    hdlr.handle(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 751, in handle
    self.emit(record)
  File "/var/projects/myproject/code/myproject/logging_config.py", line 84, in emit
    self.sender.send_exception(exc_info=(exc_type, exc_value, None), frames=reversed(inspect.getouterframes(src_frame)))
  File "/var/projects/myproject/code/myproject/logging_config.py", line 32, in send_exception
    return raygunprovider.RaygunSender.send_exception(self, *args, **kwargs)
  File "/var/projects/myproject/virtualenv/local/local/lib/python2.7/site-packages/raygun4py/raygunprovider.py", line 109, in send_exception
    return self._post(message)
  File "/var/projects/myproject/virtualenv/local/local/lib/python2.7/site-packages/raygun4py/raygunprovider.py", line 167, in _post
    log.error(e)
NameError: global name 'log' is not defined
```

**Comment by fundead** [comment]
Looks like this indeed should be calling log on the RaygunSender instance via `self`. I'll write unit tests for this case this coming week and confirm that the change fixes the issue, which if it does will be released as a point release ASAP.
