### ISSUE TITLE
AttributeError: class RaygunErrorMessage has no attribute '__mro__'

### ISSUE THREAD

**Issue by kevart** [MindscapeHQ/raygun4py#52]
Using old-style classes causes this error:

```
Traceback (most recent call last):
  File "[..]/env/lib/python2.7/site-packages/[..]/raygun/logger.py", line 34, in raygun_log
    provider.sender.send_exception(**kwargs)
  File "[..]/env/lib/python2.7/site-packages/raygun4py/raygunprovider.py", line 110, in send_exception
    return self._post(message)
  File "[..]/env/lib/python2.7/site-packages/raygun4py/raygunprovider.py", line 156, in _post 
    json = jsonpickle.encode(raygunMessage, unpicklable=False)
  File "[..]/env/lib/python2.7/site-packages/jsonpickle/__init__.py", line 131, in encode
    warn=warn)
  File "[..]/env/lib/python2.7/site-packages/jsonpickle/pickler.py", line 42, in encode 
    return backend.encode(context.flatten(value, reset=reset))
  File "[..]/env/lib/python2.7/site-packages/jsonpickle/pickler.py", line 153, in flatten
    return self._flatten(obj)
  File "[..]/env/lib/python2.7/site-packages/jsonpickle/pickler.py", line 157, in _flatten
    return self._pop(self._flatten_obj(obj))
  File "[..]/env/lib/python2.7/site-packages/jsonpickle/pickler.py", line 173, in _flatten_obj
    return flatten_func(obj)
  File "[..]/env/lib/python2.7/site-packages/jsonpickle/pickler.py", line 425, in _flatten_dict_obj
    flatten(k, v, data)
  File "[..]/env/lib/python2.7/site-packages/jsonpickle/pickler.py", line 491, in _flatten_key_value_pair
    data[k] = self._flatten(v)
  File "[..]/env/lib/python2.7/site-packages/jsonpickle/pickler.py", line 157, in _flatten
    return self._pop(self._flatten_obj(obj))
  File "[..]/env/lib/python2.7/site-packages/jsonpickle/pickler.py", line 173, in _flatten_obj
    return flatten_func(obj)
  File "[..]/env/lib/python2.7/site-packages/jsonpickle/pickler.py", line 425, in _flatten_dict_obj
    flatten(k, v, data)
  File "[..]/env/lib/python2.7/site-packages/jsonpickle/pickler.py", line 491, in _flatten_key_value_pair
    data[k] = self._flatten(v)
  File "[..]/env/lib/python2.7/site-packages/jsonpickle/pickler.py", line 157, in _flatten
    return self._pop(self._flatten_obj(obj))
  File "[..]/env/lib/python2.7/site-packages/jsonpickle/pickler.py", line 173, in _flatten_obj
    return flatten_func(obj)
  File "[..]/env/lib/python2.7/site-packages/jsonpickle/pickler.py", line 231, in _ref_obj_instance
    return self._flatten_obj_instance(obj)
  File "[..]/env/lib/python2.7/site-packages/jsonpickle/pickler.py", line 361, in _flatten_obj_instance
    if util.is_iterator(obj):
  File "[..]/env/lib/python2.7/site-packages/jsonpickle/util.py", line 337, in is_iterator
    return (isinstance(obj, collections.Iterator) and
  File "[..]/env/lib/python2.7/abc.py", line 144, in __instancecheck__
    return cls.__subclasscheck__(subtype)
  File "[..]/env/lib/python2.7/abc.py", line 180, in __subclasscheck__
    if issubclass(subclass, scls):
  File "[..]/env/lib/python2.7/abc.py", line 161, in __subclasscheck__
    ok = cls.__subclasshook__(subclass)
  File "[..]/env/lib/python2.7/site-packages/backports_abc.py", line 66, in __subclasshook__
    mro = C.__mro__
  AttributeError: class RaygunErrorMessage has no attribute '__mro__'
```

**raygun4py==3.1.3**

**Comment by kevart** [comment]
Pull request: https://github.com/MindscapeHQ/raygun4py/pull/53
