### ISSUE TITLE
AttributeError: 'dict' object has no attribute 'localVariables'

### ISSUE THREAD

**Issue by kevart** [MindscapeHQ/raygun4py#54]
```
Traceback (most recent call last):
[..]
    client.send_exception(exception=exception, userCustomData=custom_data)
  File "[..]/env/lib/python2.7/site-packages/raygun4py/raygunprovider.py", line 95, in send_exception
    errorMessage = raygunmsgs.RaygunErrorMessage(type(exception), exception, exc_traceback, options)
  File "[..]/env/lib/python2.7/site-packages/raygun4py/raygunmsgs.py", line 152, in __init__
    if frame.localVariables:
AttributeError: 'dict' object has no attribute 'localVariables'
```

**raygun4py==3.1.3**

**Comment by kevart** [comment]
Pull request: https://github.com/MindscapeHQ/raygun4py/pull/55
